# Generated by Django 4.1 on 2022-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('link', models.URLField()),
            ],
        ),
    ]
