# Generated by Django 4.1 on 2022-11-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='pdf',
            field=models.FileField(default=12, upload_to='PDFs'),
            preserve_default=False,
        ),
    ]
